steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/myapp', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/myapp']
# # Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'myapp', '--image', 'gcr.io/$PROJECT_ID/myapp', '--region', 'us-central1', '--platform', 'managed','--port','80']
images:
- gcr.io/$PROJECT_ID/myapp
# deploy container image to GKE
# - name: 'gcr.io/cloud-builders/docker'
#   args:
#   - run
#   - --filename=K8s/
#   - --image=gcr.io/$PROJECT_ID/myapp
#   - --location=us-centeal1-b
#   - --cluster=mykube




